=== CarlosPovedaBarragan/Equipos_Futbol_Americano/Equipos_Futbol_Americano/WebContent/WEB-INF/classes/xml/Jugadores.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Jugadores (Jugador+)>
<!ELEMENT Jugador (nombre, apellidos, equipo, posicion, salario)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT equipo (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ATTLIST posicion dorsal CDATA #REQUIRED> 
<!ELEMENT salario (#PCDATA)>

=== CarlosPovedaBarragan/Equipos_Futbol_Americano/Equipos_Futbol_Americano/WebContent/WEB-INF/classes/xml/Jugadores.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Jugadores SYSTEM "D:/Ufv/Eclipse/Equipos_Futbol_Americano/src/xml/Jugadores.dtd">

<Jugadores>

	<Jugador>
		<nombre>Matt</nombre>
		<apellidos>Barkley</apellidos>
		<equipo>Arizona Cardinals</equipo>
		<posicion  dorsal="#9">QB</posicion>
		<salario>1.000.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Justin</nombre>
		<apellidos>Bethel</apellidos>
		<equipo>Arizona Cardinals</equipo>
		<posicion  dorsal="#28">CB</posicion>
		<salario>1.500.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Cariel</nombre>
		<apellidos>Brooks</apellidos>
		<equipo>Arizona Cardinals</equipo>
		<posicion  dorsal="#35">DB</posicion>
		<salario>750.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>John</nombre>
		<apellidos>Brown</apellidos>
		<equipo>Arizona Cardinals</equipo>
		<posicion  dorsal="#12">WR</posicion>
		<salario>1.100.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Deone</nombre>
		<apellidos>Bucannon</apellidos>
		<equipo>Arizona Cardinals</equipo>
		<posicion  dorsal="#20">OLB</posicion>
		<salario>1.250.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Robert</nombre>
		<apellidos>Alford</apellidos>
		<equipo>Atlanta Falcons</equipo>
		<posicion  dorsal="#23">CB</posicion>
		<salario>550.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Ricardo</nombre>
		<apellidos>Allen</apellidos>
		<equipo>Atlanta Falcons</equipo>
		<posicion  dorsal="#37">FS</posicion>
		<salario>250.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Eric</nombre>
		<apellidos>Weems</apellidos>
		<equipo>Atlanta Falcons</equipo>
		<posicion  dorsal="#14">WR</posicion>
		<salario>350.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Desmond</nombre>
		<apellidos>Trufant</apellidos>
		<equipo>Atlanta Falcons</equipo>
		<posicion  dorsal="#21">CB</posicion>
		<salario>2.550.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Terron</nombre>
		<apellidos>Ward</apellidos>
		<equipo>Atlanta Falcons</equipo>
		<posicion  dorsal="#33">RB</posicion>
		<salario>760.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Javorius</nombre>
		<apellidos>Allen</apellidos>
		<equipo>Baltimore Ravens</equipo>
		<posicion  dorsal="#37">RB</posicion>
		<salario>990.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Matt</nombre>
		<apellidos>Elam</apellidos>
		<equipo>Baltimore Ravens</equipo>
		<posicion  dorsal="#26">SS</posicion>
		<salario>1.990.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Lawrence</nombre>
		<apellidos>Guy</apellidos>
		<equipo>Baltimore Ravens</equipo>
		<posicion  dorsal="#93">DE</posicion>
		<salario>190.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>James</nombre>
		<apellidos>Hurst</apellidos>
		<equipo>Baltimore Ravens</equipo>
		<posicion  dorsal="#74">T</posicion>
		<salario>390.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Timmy</nombre>
		<apellidos>Jernigan</apellidos>
		<equipo>Baltimore Ravens</equipo>
		<posicion  dorsal="#97">DE</posicion>
		<salario>1.000.500 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Tyson</nombre>
		<apellidos>Chandler</apellidos>
		<equipo>Buffalo Bills</equipo>
		<posicion  dorsal="#79">T</posicion>
		<salario>1.101.500 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Marcus</nombre>
		<apellidos>Easley</apellidos>
		<equipo>Buffalo Bills</equipo>
		<posicion  dorsal="#81">WR</posicion>
		<salario>3.100.000 $</salario>
	</Jugador>
	
	
	<Jugador>
		<nombre>Jerome</nombre>
		<apellidos>Felton</apellidos>
		<equipo>Buffalo Bills</equipo>
		<posicion  dorsal="#42">FB</posicion>
		<salario>100.000 $</salario>
	</Jugador>
	
	
	<Jugador>
		<nombre>Merrill</nombre>
		<apellidos>Noel</apellidos>
		<equipo>Buffalo Bills</equipo>
		<posicion  dorsal="#46">CB</posicion>
		<salario>1.340.123 $</salario>
	</Jugador>
	
	
	<Jugador>
		<nombre>Colton</nombre>
		<apellidos>Schmidt</apellidos>
		<equipo>Buffalo Bills</equipo>
		<posicion  dorsal="#6">P</posicion>
		<salario>120.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Kurt</nombre>
		<apellidos>Coleman</apellidos>
		<equipo>Caroline Panthers</equipo>
		<posicion  dorsal="#20">FS</posicion>
		<salario>125.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Thomas</nombre>
		<apellidos>Davis</apellidos>
		<equipo>Caroline Panthers</equipo>
		<posicion  dorsal="#58">OLB</posicion>
		<salario>725.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Daryl</nombre>
		<apellidos>Williams</apellidos>
		<equipo>Caroline Panthers</equipo>
		<posicion  dorsal="#60">OT</posicion>
		<salario>155.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Teddy</nombre>
		<apellidos>Williams</apellidos>
		<equipo>Caroline Panthers</equipo>
		<posicion  dorsal="#21">DB</posicion>
		<salario>325.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Kelvin</nombre>
		<apellidos>Benjamin</apellidos>
		<equipo>Caroline Panthers</equipo>
		<posicion  dorsal="#13">WR</posicion>
		<salario>225.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Terry</nombre>
		<apellidos>Williams</apellidos>
		<equipo>Chicago Bears </equipo>
		<posicion  dorsal="#79">DT</posicion>
		<salario>525.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Lamarr</nombre>
		<apellidos>Houston</apellidos>
		<equipo>Chicago Bears </equipo>
		<posicion  dorsal="#99">OLB</posicion>
		<salario>625.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Charles</nombre>
		<apellidos>Leno</apellidos>
		<equipo>Chicago Bears </equipo>
		<posicion  dorsal="#72">T</posicion>
		<salario>725.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Sherrick</nombre>
		<apellidos>McManis</apellidos>
		<equipo>Chicago Bears </equipo>
		<posicion  dorsal="#27">CB</posicion>
		<salario>825.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Pernell</nombre>
		<apellidos>McPhee</apellidos>
		<equipo>Chicago Bears </equipo>
		<posicion  dorsal="#92">OLB</posicion>
		<salario>425.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Shawn</nombre>
		<apellidos>Williams</apellidos>
		<equipo>Cincinnati Bengals </equipo>
		<posicion  dorsal="#69">DT</posicion>
		<salario>325.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>DeShawn</nombre>
		<apellidos>Williams</apellidos>
		<equipo>Cincinnati Bengals </equipo>
		<posicion  dorsal="#36">SS</posicion>
		<salario>125.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>A.J</nombre>
		<apellidos>Green</apellidos>
		<equipo>Cincinnati Bengals </equipo>
		<posicion  dorsal="#18">WR</posicion>
		<salario>1.325.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>A.J</nombre>
		<apellidos>Hawk</apellidos>
		<equipo>Cincinnati Bengals </equipo>
		<posicion  dorsal="#50">OLB</posicion>
		<salario>1.125.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Domata</nombre>
		<apellidos>Peko</apellidos>
		<equipo>Cincinnati Bengals </equipo>
		<posicion  dorsal="#94">DT</posicion>
		<salario>25.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Joel</nombre>
		<apellidos>Bitonio</apellidos>
		<equipo>Cleveland Browns </equipo>
		<posicion  dorsal="#75">G</posicion>
		<salario>225.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Austin</nombre>
		<apellidos>Davis</apellidos>
		<equipo>Cleveland Browns </equipo>
		<posicion  dorsal="#7">QB</posicion>
		<salario>325.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Charley</nombre>
		<apellidos>Hughlett</apellidos>
		<equipo>Cleveland Browns </equipo>
		<posicion  dorsal="#47">LS</posicion>
		<salario>255.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Randall</nombre>
		<apellidos>Telfer</apellidos>
		<equipo>Cleveland Browns </equipo>
		<posicion  dorsal="#86">TE</posicion>
		<salario>125.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Travis</nombre>
		<apellidos>Coons</apellidos>
		<equipo>Cleveland Browns </equipo>
		<posicion  dorsal="#6">K</posicion>
		<salario>1.225.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Travis</nombre>
		<apellidos>Frederick</apellidos>
		<equipo>Dallas Cowboys </equipo>
		<posicion  dorsal="#72">C</posicion>
		<salario>2.225.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Zack</nombre>
		<apellidos>Martin</apellidos>
		<equipo>Dallas Cowboys </equipo>
		<posicion  dorsal="#70">G</posicion>
		<salario>375.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>KaÂ´Lial</nombre>
		<apellidos>Glaud</apellidos>
		<equipo>Dallas Cowboys </equipo>
		<posicion  dorsal="#47">LB</posicion>
		<salario>2.550.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Rod</nombre>
		<apellidos>Smith</apellidos>
		<equipo>Dallas Cowboys </equipo>
		<posicion  dorsal="#45">RB</posicion>
		<salario>1.725.100 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Geoff</nombre>
		<apellidos>Swaim</apellidos>
		<equipo>Dallas Cowboys </equipo>
		<posicion  dorsal="#87">TE</posicion>
		<salario>5.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Zaire</nombre>
		<apellidos>Anderson</apellidos>
		<equipo>Denver Broncos </equipo>
		<posicion  dorsal="#47">LB</posicion>
		<salario>15.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Todd</nombre>
		<apellidos>Davis</apellidos>
		<equipo>Denver Broncos </equipo>
		<posicion  dorsal="#51">MLB</posicion>
		<salario>215.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Ty</nombre>
		<apellidos>Sambrailo</apellidos>
		<equipo>Denver Broncos </equipo>
		<posicion  dorsal="#74">OT</posicion>
		<salario>315.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Matt</nombre>
		<apellidos>Paradis</apellidos>
		<equipo>Denver Broncos </equipo>
		<posicion  dorsal="#61">C</posicion>
		<salario>415.000 $</salario>
	</Jugador>
	
	<Jugador>
		<nombre>Brandon</nombre>
		<apellidos>McManus</apellidos>
		<equipo>Denver Broncos </equipo>
